### ISSUE TITLE
app complains about no network connection

### ISSUE THREAD

**Issue by andreasn** [flathub/com.github.JannikHv.Gydl#1]
So not sure if this is a bug in the flatpak or in the app, but I'm unable to download any youtube videos, because the app says it has no network connection.
This is weird, because it looks like it has looking at the json-file.

**Comment by AsavarTzeth** [comment]
It is a known issue, but I have no idea how to solve it. See: https://github.com/JannikHv/gydl/issues/11

Thank you for adding an issue here though, I considered doing the same. Hopefully someone more experienced with the flatpak sandbox and GLib could be of assistance.

**Comment by TingPing** [comment]
To be completely honest, that check is stupid. You handle network failures at time of use not before-hand for this type of application.

**Comment by AsavarTzeth** [comment]
Well that confirms my instinct. I honestly thought it was redundant, but since I'm not really a developer and did not know what to replace it with I did not mention it to the developer.

**Comment by TingPing** [comment]
Just delete `get_can_reach()` and all usage. If it doesn't handle failure later that was always a bug.

**Comment by TingPing** [comment]
Btw the API `get_can_reach()` uses *should* work fine in Flatpak.

**Comment by TingPing** [comment]
Also not to be overly rude, but that codebase is fairly low quality in general and needs some major fixes.

**Comment by AsavarTzeth** [comment]
Well refactoring is planned but I don't know to what extent. I am pretty sure it was a first time project meant to learn how things work. Personally I have been looking GtkApplication and Glade for some hobby project of my own, but I am a slow learner.

It really is funny. I picked the app as a simpler target to learn flatpak packaging.

But now I feel I should not speak for the author anymore. I will make sure he sees this thread.

**Comment by TingPing** [comment]
> Personally I have been looking at GtkApplication and Glade for some hobby project of my own, but I am a slow learner.

Yup those would be good places to start. Also executing commands needs to be async (GSubprocess).

Anybody feel free to hit me up on IRC for any questions regarding that.

**Comment by legacychimera247** [comment]
well now the problem is solved, at least to me...think we can close this one?

**Comment by AsavarTzeth** [comment]
Well I do see some changes commited but the flatpak remains unchanged at this time. So unless you built your own flatpak that remains untested.

In your case it has most likely just temporarely started working, again.

**Comment by glaubersm** [comment]
this problem is still happening on Arch Linux.
Gydl flatpak build is unusable.
